import {api,esc,today,notify,allRows,currentStaff,currentData} from './cloud.mjs';
const $=id=>document.getElementById(id),money=n=>Number(n).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
let rows={ledger:[],team_members:[],clinical_records:[],partner_connections:[]},kind='income',loadVersion=0;
$('financeMonth').value=today.slice(0,7);
async function load(){const version=++loadVersion,role=currentStaff()?.role;if(!role){rows={ledger:[],team_members:[],clinical_records:[],partner_connections:[]};return;}
const tables=role==='admin'?Object.keys(rows):role==='reception'?['ledger']:['clinical_records'];
try{const values=await Promise.all(tables.map(t=>allRows(t,`${t==='partner_connections'?'partner':'created_at'}.desc`)));if(version!==loadVersion||role!==currentStaff()?.role)return;rows={ledger:[],team_members:[],clinical_records:[],partner_connections:[]};tables.forEach((t,i)=>rows[t]=values[i]);render();}catch(e){notify(e.message);}}
window.addEventListener('vitale:refresh',load);
function render(){const d=currentData(),role=currentStaff()?.role;
const options='<option value="">Selecione</option>'+d.students.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('');$('paymentStudent').innerHTML=options;$('clinicalStudent').innerHTML=options;
const list=rows.ledger.filter(r=>r.paid_on.startsWith($('financeMonth').value)),total=k=>list.filter(r=>r.kind===k).reduce((v,r)=>v+Number(r.amount),0);
$('financeSummary').innerHTML=`<div class="card">Recebimentos<b>${money(total('income'))}</b></div>`+(role==='admin'?`<div class="card">Despesas<b>${money(total('expense'))}</b></div><div class="card">Saldo do mês<b>${money(total('income')-total('expense'))}</b></div>`:'');
const costs=['materiais','pessoal','outros'].map(c=>({category:c,total:list.filter(r=>r.kind==='expense'&&r.category===c).reduce((v,r)=>v+Number(r.amount),0)})),max=Math.max(1,...costs.map(c=>c.total));
$('costChart').innerHTML='<h3>Custos por categoria</h3>'+costs.map(c=>`<div class="chart-row"><span>${esc(c.category)}</span><div class="chart-track"><div class="chart-bar" style="width:${c.total/max*100}%" role="img" aria-label="${esc(c.category)}: ${money(c.total)}"></div></div><strong>${money(c.total)}</strong></div>`).join('');
const name=id=>d.students.find(s=>s.id===id)?.name||'—';
$('ledgerRows').innerHTML=list.map(r=>`<tr><td>${esc(r.paid_on.split('-').reverse().join('/'))}</td><td>${esc(r.description)}<br><small>${esc(r.method)}</small></td><td>${esc(r.category)}</td><td>${esc(name(r.student_id))}</td><td>${r.kind==='expense'?'−':''}${money(r.amount)}</td></tr>`).join('')||'<tr><td colspan="5">Nenhum lançamento neste mês.</td></tr>';
$('teamRows').innerHTML=rows.team_members.map(r=>`<tr><td>${esc(r.name)}</td><td>${esc(r.email)}</td><td>${r.role==='professional'?'Fisioterapeuta':'Recepção'}</td><td>${esc(r.registration||'—')}</td><td>${r.user_id?'Habilitado':'Acesso pendente'}</td></tr>`).join('')||'<tr><td colspan="5">Nenhum profissional cadastrado.</td></tr>';
$('clinicalRows').innerHTML=rows.clinical_records.map(r=>`<article class="card"><h3>${esc(r.kind)} · ${esc(name(r.student_id))}</h3><small>${esc(r.recorded_on)} · ${esc(d.professionals.find(p=>p.user_id===r.professional_id)?.name||'Administrador')}</small><h4>Queixa e histórico</h4><p>${esc(r.complaint||'—')}</p><h4>Achados</h4><p>${esc(r.findings||'—')}</p><h4>Conduta / plano</h4><p>${esc(r.plan)}</p></article>`).join('')||'<p>Nenhum registro clínico disponível.</p>';
$('partnerRows').innerHTML=['Wellhub','TotalPass'].map(p=>{const r=rows.partner_connections.find(r=>r.partner===p);return `<article class="card"><h3>${p}</h3><strong>Conexão pendente</strong><p>Identificação: ${esc(r?.clinic_identifier||'Não cadastrada')}</p><p>${esc(r?.notes||'Aguardando credenciamento e acessos oficiais.')}</p></article>`;}).join('');}
$('financeMonth').onchange=render;
function openLedger(k){kind=k;$('ledgerForm').reset();$('ledgerTitle').textContent=k==='income'?'Lançar pagamento':'Lançar despesa';$('paymentStudentLabel').classList.toggle('hidden',k==='expense');$('paymentStudent').required=k==='income';$('expenseCategoryLabel').classList.toggle('hidden',k==='income');$('ledgerForm').elements.paid_on.value=today;$('ledgerDialog').showModal();}
$('newPayment').onclick=()=>openLedger('income');$('newExpense').onclick=()=>openLedger('expense');$('newTeam').onclick=()=>$('teamDialog').showModal();$('newClinical').onclick=()=>{$('clinicalForm').elements.recorded_on.value=today;$('clinicalDialog').showModal();};
async function submit(form,action,dialog,message){form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('button');button.disabled=true;try{await action(Object.fromEntries(new FormData(form)));await load();if(dialog)$(dialog).close();form.reset();notify(message);}catch(e){notify(e.message);}finally{button.disabled=false;}};}
submit($('ledgerForm'),d=>api('/rest/v1/ledger',{method:'POST',body:JSON.stringify({...d,kind,amount:Number(d.amount),student_id:kind==='income'?d.student_id:null,category:kind==='income'?'pagamento':d.category})}),'ledgerDialog','Lançamento registrado.');
submit($('teamForm'),async d=>{await api('/rest/v1/rpc/save_team',{method:'POST',body:JSON.stringify({p_name:d.name,p_email:d.email,p_role:d.role,p_registration:d.registration||null})});window.dispatchEvent(new Event('vitale:team'));},'teamDialog','Cadastro salvo. Consulte a coluna Acesso para verificar a habilitação.');
submit($('clinicalForm'),d=>api('/rest/v1/clinical_records',{method:'POST',body:JSON.stringify(d)}),'clinicalDialog','Registro clínico salvo.');
submit($('partnerForm'),d=>api('/rest/v1/partner_connections?on_conflict=partner',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify({...d,updated_at:new Date().toISOString()})}),null,'Configuração salva. A conexão oficial continua pendente.');
if(currentStaff())load();
