create or replace function vitale_private.role() returns text language sql stable security definer set search_path='' as $$ select role from public.staff where user_id=auth.uid() and active $$;
revoke all on function vitale_private.role() from public,anon;
grant usage on schema vitale_private to authenticated;
grant execute on function vitale_private.role() to authenticated;
create table public.team_members(id uuid primary key default gen_random_uuid(), name text not null check(length(trim(name))>0),email text not null unique,role text not null check(role in ('professional','reception')),registration text,active boolean not null default true,user_id uuid unique references auth.users(id),created_at timestamptz not null default now());
alter table public.team_members enable row level security;
create policy team_admin on public.team_members for select to authenticated using(vitale_private.role()='admin');
grant select on public.team_members to authenticated;
create or replace function vitale_private.save_team(p_name text,p_email text,p_role text,p_registration text) returns uuid language plpgsql security definer set search_path='' as $$ declare uid uuid; mid uuid; begin
if vitale_private.role() is distinct from 'admin' then raise exception 'Acesso restrito'; end if;
if p_role not in ('professional','reception') or length(trim(p_name))=0 then raise exception 'Dados inválidos'; end if;
select id into uid from auth.users where lower(email)=lower(trim(p_email));
if exists(select 1 from public.staff where user_id=uid and role='admin') then raise exception 'Administrador não pode ser alterado nesta tela'; end if;
insert into public.team_members(name,email,role,registration,user_id) values(trim(p_name),lower(trim(p_email)),p_role,p_registration,uid) on conflict(email) do update set name=excluded.name,role=excluded.role,registration=excluded.registration,user_id=excluded.user_id returning id into mid;
if uid is not null then
insert into public.staff(user_id,name,role,active) values(uid,trim(p_name),p_role,true) on conflict(user_id) do update set name=excluded.name,role=excluded.role,active=true;
if p_role='professional' then insert into public.professionals(user_id,name,active) values(uid,trim(p_name),true) on conflict(user_id) do update set name=excluded.name,active=true;
else update public.professionals set active=false where user_id=uid; end if;
end if; return mid; end $$;
revoke all on function vitale_private.save_team(text,text,text,text) from public,anon;
grant execute on function vitale_private.save_team(text,text,text,text) to authenticated;
create function public.save_team(p_name text,p_email text,p_role text,p_registration text) returns uuid language sql security invoker set search_path='' as $$ select vitale_private.save_team(p_name,p_email,p_role,p_registration) $$;
revoke all on function public.save_team(text,text,text,text) from public,anon;
grant execute on function public.save_team(text,text,text,text) to authenticated;
create table public.ledger(id uuid primary key default gen_random_uuid(),kind text not null check(kind in ('income','expense')),category text not null check(category in ('pagamento','materiais','pessoal','outros')),student_id uuid references public.students(id),description text not null check(length(trim(description))>0),amount numeric(12,2) not null check(amount>0),paid_on date not null,method text not null default 'Pix',recorded_by uuid not null default auth.uid() references auth.users(id),created_at timestamptz not null default now(),check((kind='income' and category='pagamento' and student_id is not null) or (kind='expense' and category<>'pagamento' and student_id is null)));
alter table public.ledger enable row level security;
create policy ledger_read on public.ledger for select to authenticated using(vitale_private.role()='admin' or (vitale_private.role()='reception' and kind='income'));
create policy ledger_insert on public.ledger for insert to authenticated with check(recorded_by=auth.uid() and (vitale_private.role()='admin' or (vitale_private.role()='reception' and kind='income')));
grant select,insert on public.ledger to authenticated;
create index ledger_paid_on on public.ledger(paid_on);
create table public.clinical_records(id uuid primary key default gen_random_uuid(),student_id uuid not null references public.students(id),professional_id uuid not null default auth.uid() references public.staff(user_id),kind text not null check(kind in ('Avaliação','Evolução','Guia')),recorded_on date not null,complaint text not null default '',findings text not null default '',plan text not null check(length(trim(plan))>0),created_at timestamptz not null default now());
alter table public.clinical_records enable row level security;
create policy clinical_read on public.clinical_records for select to authenticated using(vitale_private.role()='admin' or(vitale_private.role()='professional' and professional_id=auth.uid()));
create policy clinical_insert on public.clinical_records for insert to authenticated with check(professional_id=auth.uid() and (vitale_private.role()='admin' or(vitale_private.role()='professional' and exists(select 1 from public.appointments a where a.student_id=clinical_records.student_id and a.professional_id=auth.uid()))));
grant select,insert on public.clinical_records to authenticated;
create index clinical_student on public.clinical_records(student_id,recorded_on);
create table public.partner_connections(partner text primary key check(partner in ('Wellhub','TotalPass')),clinic_identifier text not null default '',notes text not null default '',updated_at timestamptz not null default now());
alter table public.partner_connections enable row level security;
create policy partner_admin on public.partner_connections for all to authenticated using(vitale_private.role()='admin') with check(vitale_private.role()='admin');
grant select,insert,update on public.partner_connections to authenticated;
